### ISSUE TITLE
列表下拉刷新有bug

### ISSUE THREAD

**Issue by waltcow** [just4fun/uestc-bbs-react-native#1]
列表下拉刷新，停着不放，列表会出现闪动

**Comment by just4fun** [comment]
你好，

那是组件[react-native-refreshable-listview](https://github.com/jsdf/react-native-refreshable-listview)的一个known issue，可以参考[这里](https://github.com/jsdf/react-native-refreshable-listview/issues/32)。

目前FB官方没有提供refreshable的listview，所以只能找社区实现的版本。

不过这个组件已经有一些[PR](https://github.com/jsdf/react-native-refreshable-listview/pulls)想解决这个问题，作者也给了回复表示正在working on new branch for this。

另外社区也有这个组件的[替代品](https://github.com/Shuangzuan/RCTRefreshControl)，没有这个issue，但因为我这个repo还在持续实现bbs的[功能](https://github.com/just4fun/uestc-bbs-react-native#existing-functionalities)，所以暂时没有替换组件或者refactor的打算。后续应该会在react-native-refreshable-listview新版本release后进行升级。

感谢关注。

**Comment by waltcow** [comment]
感谢告知

**Comment by TossShinHwa** [comment]
![f7f593d9211181b3f55c0a0c2dcf82a4](https://cloud.githubusercontent.com/assets/3007674/12442035/7e2dd780-bf87-11e5-8fc5-bd44a696a18b.png)

**Comment by zyu** [comment]
npm install 的时候停在 react-tools aft 哪里就不动了

**Comment by just4fun** [comment]
@zyu 尝试淘宝的npm镜像吧，安装会快一些。

**Comment by just4fun** [comment]
Hey all,

I will close this issue once [react-native-refreshable-listview](https://github.com/jsdf/react-native-refreshable-listview) publish 2.0 final release.

Thank you.

**Comment by TossShinHwa** [comment]
![d240621ff4f0b7fc3314092a4964a04c](https://cloud.githubusercontent.com/assets/3007674/13313912/90218b32-dbdc-11e5-9fcc-c04a85106e22.png)

**Comment by zyu** [comment]
能否给一个测试的帐号啊

2016-02-25 16:26 GMT+08:00 Zack Yang <notifications@github.com>:

**Comment by just4fun** [comment]
@zyu ，这个确实有点为难，论坛账号是跟学号绑定的，不敢随便提供。
不过我在todo list里加了一项fixture data/mock data，等这个完成后就可以测试了。

**Comment by just4fun** [comment]
@waltcow 

Sorry for the too delayed update, I just replaced 3rd party refreshable listview component with React Native built-in component [RefreshControl](https://facebook.github.io/react-native/docs/refreshcontrol.html) (which is released via v0.18.0, and I upgraded RN from v0.14.0 to v0.21.0 several weeks ago), you can refer this [commit](https://github.com/just4fun/uestc-bbs-react-native/commit/70bfb7c84d0ef316732b641dfcf805fb6ba24e28) and pull latest code to try it out.

Close this issue as fixed.

**Comment by xudao520** [comment]
@just4fun 
![image](https://cloud.githubusercontent.com/assets/12093709/15495362/ea23bcce-21c1-11e6-9feb-ba0b4f73dee6.png)这个pull to refresh文本怎么替换的

**Comment by just4fun** [comment]
@xudao520 我用的FB提供的RefreshControl，请参考官方文档。

**Comment by xudao520** [comment]
@just4fun 那你没有用ListView？

**Comment by just4fun** [comment]
@xudao520 
https://github.com/just4fun/uestc-bbs-react-native/blob/master/app/components/TopicList.js#L82-L100
http://facebook.github.io/react-native/docs/refreshcontrol.html

还是先把官方文档读一遍吧。

**Comment by xudao520** [comment]
@just4fun 谢谢，我应该去看下英文文档的，一直在看中文文档才这么认为

**Comment by just4fun** [comment]
@xudao520 
前端的东西都不要看中文文档。

**Comment by xudao520** [comment]
@just4fun 对的，踩坑了
